name: yuro_cli
description: A sample command-line for yuro.
version: 0.6.0
homepage: https://github.com/YuroLtd/yuro_cli

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
   http: ^0.13.5
   path: ^1.8.2
   yaml: ^3.1.1
   args: ^2.3.1
   process_run: ^0.12.3+2
   dart_style: ^2.2.3
   ansicolor: ^2.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0


executables:
  yuro: yuro_cli