name: yuro_cli
description: A sample command-line application.
version: 0.3.2
homepage: https://github.com/YuroLtd/yuro_cli.git

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  path: ^1.7.0
  yaml: ^3.1.0
  args: ^2.1.0
  process_run: ^0.12.1
  ansicolor: ^2.0.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.4

executables:
  yuro: yuro_cli
