name: yuro_cli
description: A command-line for yuro.
version: 0.5.0
homepage: https://github.com/YuroLtd/yuro_cli

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.4
  path: ^1.8.1
  yaml: ^3.1.0
  args: ^2.3.0
  process_run: ^0.12.3+1
  dart_style: ^2.2.1
  ansicolor: ^2.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0


executables:
  yuro: yuro_cli
